export const STRINGS = {
  fr: {
    dashboard:'Tableau de bord',batteries:'Batteries',foyers:'Foyers',demandes:'Demandes',allocation:'Allocation',rapports:'Rapports',utilisateurs:'Utilisateurs',
    refresh:'Actualiser',loading:'Chargement...',save:'Enregistrer',cancel:'Annuler',delete:'Supprimer',edit:'Modifier',add:'Ajouter',confirm:'Confirmer',yes:'Oui',no:'Non',search:'Rechercher...',no_data:'Aucune donnée',error:'Erreur',success:'Succès',close:'Fermer',details:'Détails',actions:'Actions',status:'Statut',created_at:'Créé le',
    kpi_battery:'Énergie stockée',kpi_foyers:'Foyers enregistrés',kpi_demandes:'Demandes en attente',kpi_rapports:'Rapports générés',battery_state:'État des batteries',pending_dem:'Demandes en attente',last_reports:'Derniers rapports',system_online:'Système en ligne',total_capacity:'Capacité totale',current_level:'Niveau actuel',solar_forecast:'Prévision solaire',empty_wait:'En attente...',
    battery_id:'ID Batterie',battery_name:'Nom',battery_cap_total:'Capacité totale (kWh)',battery_cap_actual:'Niveau actuel (kWh)',battery_threshold:'Seuil critique (kWh)',battery_location:'Emplacement',battery_add:'Ajouter une batterie',battery_edit:'Modifier la batterie',battery_delete_confirm:'Supprimer cette batterie ?',battery_critical:'CRITIQUE',battery_low:'Faible',battery_ok:'Normal',battery_full:'Plein',battery_alert:'Alertes batteries',battery_below_threshold:'En dessous du seuil',
    foyer_id:'ID Foyer',foyer_nom:'Nom du foyer',foyer_adresse:'Adresse',foyer_priorite:'Priorité',foyer_consommation:'Consommation (kWh)',foyer_add:'Ajouter un foyer',foyer_edit:'Modifier le foyer',foyer_delete_confirm:'Supprimer ce foyer ?',foyer_history:'Historique de consommation',priority_high:'Haute',priority_medium:'Moyenne',priority_low:'Basse',
    demande_id:'ID Demande',demande_foyer:'Foyer',demande_kwh:'Quantité (kWh)',demande_statut:'Statut',demande_add:'Nouvelle demande',demande_edit:'Modifier la demande',demande_delete_confirm:'Supprimer cette demande ?',demande_accepted:'Acceptée',demande_pending:'En attente',demande_rejected:'Rejetée',demande_date:'Date',demande_declare:'Déclarer un besoin',
    alloc_run:"Lancer l'allocation",alloc_compare:'Comparer les méthodes',alloc_forecast:'Prévision solaire',alloc_knapsack:'Optimisation Knapsack',alloc_fifo:"FIFO (ordre d'arrivée)",alloc_equal:'Partage égal',alloc_result:'Résultat allocation',alloc_accepted:'Demandes acceptées',alloc_rejected:'Demandes rejetées',alloc_kwh_total:'kWh alloués',alloc_satisfaction:'Taux de satisfaction',alloc_running:'Calcul en cours...',alloc_tomorrow_am:'Demain matin',alloc_tomorrow_pm:'Demain soir',alloc_energy_kwh:'Énergie prévue (kWh)',alloc_method:'Méthode',forecast_history:'Données historiques',
    rapport_id:'ID Rapport',rapport_consommation:'Consommation totale',rapport_allocation:'Allocation totale',rapport_alertes:'Alertes',rapport_date:'Date du rapport',rapport_details:'Détails du rapport',rapport_delete_confirm:'Supprimer ce rapport ?',rapport_generate:'Générer un rapport',
    user_id:'ID Utilisateur',user_nom:'Nom',user_email:'Email',user_role:'Rôle',user_delete_confirm:'Supprimer cet utilisateur ?',role_responsable:'Responsable',role_villageois:'Villageois',role_admin:'Administrateur',
    theme_dark:'Mode sombre',theme_light:'Mode clair',lang_fr:'Français',lang_mg:'Malagasy',settings:'Paramètres',appearance:'Apparence',language:'Langue',
  },
  mg: {
    dashboard:'Takelaka',batteries:'Bateria',foyers:'Trano',demandes:'Fangatahana',allocation:'Fizarana',rapports:'Tatitra',utilisateurs:'Mpampiasa',
    refresh:'Manavao',loading:'Miandry...',save:'Tehirizo',cancel:'Ajanony',delete:'Fafao',edit:'Ovay',add:'Hanampy',confirm:'Manamarina',yes:'Eny',no:'Tsia',search:'Hikaroka...',no_data:'Tsy misy angona',error:'Hadisoana',success:'Nahomby',close:'Akatona',details:'Antsipiriany',actions:'Hetsika',status:'Toe-javatra',created_at:"Noforonina tamin'ny",
    kpi_battery:'Angovo voatahiry',kpi_foyers:'Trano voarakitra',kpi_demandes:'Fangatahana miandry',kpi_rapports:'Tatitra noforonina',battery_state:"Toetran'ny bateria",pending_dem:'Fangatahana miandry',last_reports:'Tatitra farany',system_online:'Rafitra mifandray',total_capacity:'Fahafahana manontolo',current_level:"Haavon'ny ankehitriny",solar_forecast:"Vinavinan'ny masoandro",empty_wait:'Miandry...',
    battery_id:'Laharana Bateria',battery_name:'Anarana',battery_cap_total:'Fahafahana manontolo (kWh)',battery_cap_actual:"Haavon'ny ankehitriny (kWh)",battery_threshold:'Fetra marisika (kWh)',battery_location:'Toerana',battery_add:'Hanampy bateria',battery_edit:'Ovay ny bateria',battery_delete_confirm:'Fafao ity bateria ity?',battery_critical:'MARISIKA',battery_low:'Ambany',battery_ok:'Mahazatra',battery_full:'Feno',battery_alert:'Fampitandremana bateria',battery_below_threshold:'Ambany ny fetra',
    foyer_id:'Laharana Trano',foyer_nom:"Anarana ny trano",foyer_adresse:'Adiresy',foyer_priorite:'Laharam-pahamehana',foyer_consommation:'Fampiasana (kWh)',foyer_add:'Hanampy trano',foyer_edit:'Ovay ny trano',foyer_delete_confirm:'Fafao ity trano ity?',foyer_history:"Tantaran'ny fampiasana",priority_high:'Avo',priority_medium:'Antonony',priority_low:'Ambany',
    demande_id:'Laharana Fangatahana',demande_foyer:'Trano',demande_kwh:"Isan'ny (kWh)",demande_statut:'Toe-javatra',demande_add:'Fangatahana vaovao',demande_edit:'Ovay ny fangatahana',demande_delete_confirm:'Fafao ity fangatahana ity?',demande_accepted:'Noraisina',demande_pending:'Miandry',demande_rejected:'Nolavina',demande_date:'Daty',demande_declare:'Manambara filana',
    alloc_run:'Manomboka fizarana',alloc_compare:'Ampitahao ny fomba',alloc_forecast:"Vinavinan'ny masoandro",alloc_knapsack:'Fanafainganana Knapsack',alloc_fifo:"FIFO (filaharan'ny fiantombohan)",alloc_equal:'Fizarana mitovy',alloc_result:'Vokatra fizarana',alloc_accepted:'Fangatahana noraisina',alloc_rejected:'Fangatahana nolavina',alloc_kwh_total:'kWh nozaraina',alloc_satisfaction:"Tahan'ny fahafaham-po",alloc_running:'Mandritra ny kajy...',alloc_tomorrow_am:'Rahampitso maraina',alloc_tomorrow_pm:'Rahampitso hariva',alloc_energy_kwh:'Angovo voatokana (kWh)',alloc_method:'Fomba',forecast_history:'Angona taloha',
    rapport_id:'Laharana Tatitra',rapport_consommation:'Fampiasana manontolo',rapport_allocation:'Fizarana manontolo',rapport_alertes:'Fampitandremana',rapport_date:"Datin'ny tatitra",rapport_details:'Antsipiriany tatitra',rapport_delete_confirm:'Fafao ity tatitra ity?',rapport_generate:'Mamorona tatitra',
    user_id:'Laharana Mpampiasa',user_nom:'Anarana',user_email:'Mailaka',user_role:'Andraikitra',user_delete_confirm:'Fafao ity mpampiasa ity?',role_responsable:"Tompon'andraikitra",role_villageois:'Mponina',role_admin:'Administratora',
    theme_dark:'Modely maizina',theme_light:'Modely mazava',lang_fr:'Frantsay',lang_mg:'Malagasy',settings:'Fikirana',appearance:'Endriky',language:'Fiteny',
  },
};

export function t(lang, key) {
  const l = STRINGS[lang] ? lang : 'fr';
  return STRINGS[l][key] || STRINGS.fr[key] || key;
}
